### ISSUE TITLE
Files not found during build

### ISSUE THREAD

**Issue by WCMoses** [VahidN/OpenCVSharp-Samples#2]
I am trying to compile the samples but keep encountering errors of this variety:

Error       Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\msvcp120.dll" because it was not found.   OpenCVSharpSample01 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets 4105    

I have restored the nuget packages. All the references (at least for sample1, which is what I'm trying to build) are found.
It looks like I am forgetting to configure something, but for the life of me, I can't figure it out.

Any thoughts would be appreciated.

Here is the build output on "normal" verbosity:
1>------ Rebuild All started: Project: OpenCVSharpSample01, Configuration: Debug Any CPU ------
1>Build started 1/22/2016 8:25:57 PM.
1>CoreClean:
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.Blob.dll".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.CPlusPlus.dll".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.dll".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.Extensions.dll".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.UserInterface.dll".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.xml".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.Blob.xml".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.CPlusPlus.xml".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\bin\Debug\OpenCvSharp.Extensions.xml".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\obj\Debug\OpenCVSharpSample01.exe".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\obj\Debug\OpenCVSharpSample01.pdb".
1>  Deleting file "C:\Devtests\GitRepos\OpenCVSharpSample01\obj\Debug\OpenCVSharpSample01.csprojResolveAssemblyReference.cache".
1>RestorePackages:
1>  "C:\Devtests\GitRepos.nuget\NuGet.exe" install "C:\Devtests\GitRepos\OpenCVSharpSample01\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\Devtests\GitRepos\ "
1>  Restoring NuGet packages...
1>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
1>  All packages listed in packages.config are already installed.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>  C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll" /reference:C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.Blob.dll /reference:C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.CPlusPlus.dll /reference:C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.dll /reference:C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.Extensions.dll /reference:C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.UserInterface.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\PresentationCore.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Drawing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Windows.Forms.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\WindowsBase.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\OpenCVSharpSample01.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets\MinimumRecommendedRules.ruleset" /target:exe /utf8output Program.cs Properties\AssemblyInfo.cs "C:\Users\Chris\AppData\Local\Temp.NETFramework,Version=v4.0.AssemblyAttributes.cs"
1>_CopyFilesMarkedCopyLocal:
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.Blob.dll" to "bin\Debug\OpenCvSharp.Blob.dll".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.CPlusPlus.dll" to "bin\Debug\OpenCvSharp.CPlusPlus.dll".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.dll" to "bin\Debug\OpenCvSharp.dll".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.Extensions.dll" to "bin\Debug\OpenCvSharp.Extensions.dll".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.UserInterface.dll" to "bin\Debug\OpenCvSharp.UserInterface.dll".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.xml" to "bin\Debug\OpenCvSharp.xml".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.Blob.xml" to "bin\Debug\OpenCvSharp.Blob.xml".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.CPlusPlus.xml" to "bin\Debug\OpenCvSharp.CPlusPlus.xml".
1>  Copying file from "C:\Devtests\GitRepos\packages\OpenCvSharp-AnyCPU.2.4.10.20150320\lib\net40\OpenCvSharp.Extensions.xml" to "bin\Debug\OpenCvSharp.Extensions.xml".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\msvcp120.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\msvcr120.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\OpenCvSharpExtern.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_calib3d2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_contrib2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_core2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_features2d2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_ffmpeg2410_64.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_flann2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_gpu2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_highgui2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_imgproc2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_legacy2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_ml2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_nonfree2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_objdetect2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_ocl2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_photo2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_stitching2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_superres2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_video2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x64\opencv_videostab2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\msvcp120.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\msvcr120.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\OpenCvSharpExtern.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_calib3d2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_contrib2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_core2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_features2d2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_ffmpeg2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_flann2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_gpu2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_highgui2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_imgproc2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_legacy2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_ml2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_nonfree2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_objdetect2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_ocl2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_photo2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_stitching2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_superres2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_video2410.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Devtests\GitRepos\OpenCVSharpSample01\dll\x86\opencv_videostab2410.dll" because it was not found.
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.40
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by VahidN** [comment]
In the following folder
`packages\OpenCvSharp-AnyCPU.2.4.10.20150604\NativeDlls`
you should have these 2 folders:
`x64`
`x86`

Copy them to the `bin\Debug\dll` folder and also `root folder\dll` of each sample separately! (it should be copied automatically by the NuGet)
So now you should have `dll\x64` & `dll\x86` folders in the `root folder` and also
`bin\Debug\dll\x64`
`bin\Debug\dll\x86`

**Comment by VahidN** [comment]
Also you can try this command
`PM> update-package -reinstall`
