### ISSUE TITLE
Sample 18 Access Violation

### ISSUE THREAD

**Issue by M0J0R1S1NG** [VahidN/OpenCVSharp-Samples#4]
When you run sample 18

thie line below  from the DoOcr() function in SimpleOCR class

var detectedClass = (int)kNearest.FindNearest(result, 1, results, neighborResponses, dists); 

cause memory violation.

Ive tried to fix but no luck yet.

BTW good work!

A

**Comment by VahidN** [comment]
[Reported here](https://github.com/shimat/opencvsharp/issues/306).

**Comment by VahidN** [comment]
Try the latest beta version:
```
PM> Install-Package OpenCvSharp3-AnyCPU -Source https://ci.appveyor.com/nuget/opencvsharp -IncludePrerelease
```

**Comment by M0J0R1S1NG** [comment]
Fix works access violation gone.  No other issues with sample 18 that I have found. Closing
Good Work @VahidN

**Comment by surajtarade18** [comment]
Hi I got also same issue please help me to get it done.
https://ci.appveyor.com/nuget/opencvsharp%20-IncludePrerelease this link is also not working.

**Comment by VahidN** [comment]
[It works. Just update your nuget packages.](https://github.com/VahidN/OpenCVSharp-Samples/issues/8#issuecomment-314121668)

**Comment by surajtarade18** [comment]
I got error while updating nugget package can you please send me dll if possible.

**Comment by VahidN** [comment]
I tested it again and it works. This should be the content of your `packages.config` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="OpenCvSharp3-AnyCPU" version="3.2.0.20170419" targetFramework="net40" />
</packages>
```
Make sure you have installed the last version:
```
PM> Install-Package OpenCvSharp3-AnyCPU -Version 3.2.0.20170419
```

**Comment by surajtarade18** [comment]
Hi I got below error

Install-Package : 'OpenCvSharp3-AnyCPU' already has a dependency defined for 'N
ETStandard.Library'.
At line:1 char:16
+ Install-Package <<<<  OpenCvSharp3-AnyCPU -Version 3.2.0.20170419
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOper 
   ationException
    + FullyQualifiedErrorId : System.InvalidOperationException,ICSharpCode.Pac 
   kageManagement.Cmdlets.InstallPackageCmdlet

**Comment by VahidN** [comment]
That error means you should update your old `NuGet Package Manager`. 

> Go to Visual Studio > Tools > Extension and Updates
> Find Updates in left accordion menu, Go to Visual Studio Gallery.
> You will find a update for Nuget.

**Comment by surajtarade18** [comment]
Hi

after updating Nuget Package Manager I got error

Install-Package : 'OpenCvSharp3-AnyCPU' already has a dependency defined for 'NETStandard.Library'.
At line:1 char:16
+ Install-Package <<<<  OpenCvSharp3-AnyCPU -Version 3.2.0.20170419 
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by surajtarade18** [comment]
Hi if possible can you please mail me complete code with package and dll please
