### ISSUE TITLE
How to detect car with stream camera?

### ISSUE THREAD

**Issue by ghost** [VahidN/OpenCVSharp-Samples#5]
Hi,
    How to detect car with stream camera?
Thanks.

**Comment by VahidN** [comment]
You need to combine these 2 samples:
[Sample06](https://github.com/VahidN/OpenCVSharp-Samples/tree/master/OpenCVSharpSample06WinForms): How to use VideoCapture and WebCams.
[Sample16](https://github.com/VahidN/OpenCVSharp-Samples/tree/master/OpenCVSharpSample16): How to train your own detector using CascadeClassifier.
![veccar](https://cloud.githubusercontent.com/assets/766010/23017327/102a6ef8-f44f-11e6-8052-8108ff4fd884.png)
